#!/bin/bash

# Update system
apt update -y
apt upgrade -y

# Install Docker
apt install -y docker.io
systemctl enable docker
systemctl start docker

# Install Docker Compose
curl -L "https://github.com/docker/compose/releases/download/v2.28.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Jenkins home for data persistence
mkdir -p /var/jenkins_home
chown -R ubuntu:ubuntu /var/jenkins_home

# Install git
apt install -y git

# Clone Docker Compose repo
sudo -u ubuntu git clone https://github.com/Mohanchandra7
cd /home/ubuntu/jenkins-docker

# Launch Jenkins container
sudo -u ubuntu docker-compose up -d
